// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DataAccess;

#nullable disable

namespace MovieApp.DataAccess.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    [Migration("20220912205347_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2061),
                            PosterUrl = "some image url",
                            Title = "Star wars episode 4",
                            UserId = 1,
                            Year = 1987
                        },
                        new
                        {
                            Id = 2,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2099),
                            PosterUrl = "some image url",
                            Title = "Star wars episode 5",
                            UserId = 1,
                            Year = 1987
                        },
                        new
                        {
                            Id = 3,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2102),
                            PosterUrl = "some image url",
                            Title = "Star wars episode 6",
                            UserId = 1,
                            Year = 1987
                        },
                        new
                        {
                            Id = 4,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2104),
                            PosterUrl = "some image url",
                            Title = "Star wars episode 7",
                            UserId = 1,
                            Year = 1987
                        },
                        new
                        {
                            Id = 5,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2107),
                            PosterUrl = "some image url",
                            Title = "Harry Potter 1",
                            UserId = 2,
                            Year = 1987
                        },
                        new
                        {
                            Id = 6,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2110),
                            PosterUrl = "some image url",
                            Title = "Harry Potter 2",
                            UserId = 2,
                            Year = 1987
                        },
                        new
                        {
                            Id = 7,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2113),
                            PosterUrl = "some image url",
                            Title = "Harry Potter 3",
                            UserId = 2,
                            Year = 1987
                        },
                        new
                        {
                            Id = 8,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2115),
                            PosterUrl = "some image url",
                            Title = "Harry Potter 4",
                            UserId = 2,
                            Year = 1987
                        },
                        new
                        {
                            Id = 9,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2119),
                            PosterUrl = "some image url",
                            Title = "Harry Potter 5",
                            UserId = 2,
                            Year = 1987
                        },
                        new
                        {
                            Id = 10,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2122),
                            PosterUrl = "some image url",
                            Title = "Movie 1",
                            UserId = 3,
                            Year = 1987
                        },
                        new
                        {
                            Id = 11,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2124),
                            PosterUrl = "some image url",
                            Title = "Movie 2",
                            UserId = 3,
                            Year = 1987
                        },
                        new
                        {
                            Id = 12,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2127),
                            PosterUrl = "some image url",
                            Title = "Movie 3",
                            UserId = 3,
                            Year = 1987
                        },
                        new
                        {
                            Id = 13,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2130),
                            PosterUrl = "some image url",
                            Title = "Movie 4",
                            UserId = 3,
                            Year = 1987
                        },
                        new
                        {
                            Id = 14,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2133),
                            PosterUrl = "some image url",
                            Title = "Movie 5",
                            UserId = 3,
                            Year = 1987
                        },
                        new
                        {
                            Id = 15,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2136),
                            PosterUrl = "some image url",
                            Title = "Movie 6",
                            UserId = 4,
                            Year = 1987
                        },
                        new
                        {
                            Id = 16,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2138),
                            PosterUrl = "some image url",
                            Title = "Movie 7",
                            UserId = 4,
                            Year = 1987
                        },
                        new
                        {
                            Id = 17,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2141),
                            PosterUrl = "some image url",
                            Title = "Movie 8",
                            UserId = 4,
                            Year = 1987
                        },
                        new
                        {
                            Id = 18,
                            Description = "description goes here",
                            Genre = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2144),
                            PosterUrl = "some image url",
                            Title = "Movie 9",
                            UserId = 4,
                            Year = 1987
                        });
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.ReviewDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Review", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2171),
                            Rating = 5,
                            Review = "Review from user 1 - 1 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2174),
                            Rating = 5,
                            Review = "Review from user 1 - 2 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 3,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2177),
                            Rating = 5,
                            Review = "Review from user 1 - 3 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 4,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2180),
                            Rating = 5,
                            Review = "Review from user 1 - 4 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 5,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2182),
                            Rating = 5,
                            Review = "Review from user 1 - 5 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 6,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2185),
                            Rating = 5,
                            Review = "Review from user 1 - 6 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 7,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2188),
                            Rating = 5,
                            Review = "Review from user 1 - 7 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 8,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2190),
                            Rating = 5,
                            Review = "Review from user 1 - 8 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 9,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2193),
                            Rating = 5,
                            Review = "Review from user 1 - 9 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 10,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2196),
                            Rating = 5,
                            Review = "Review from user 1 - 10 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 11,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2198),
                            Rating = 5,
                            Review = "Review from user 1 - 11 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 12,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2201),
                            Rating = 5,
                            Review = "Review from user 1 - 12 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 13,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2204),
                            Rating = 5,
                            Review = "Review from user 1 - 13 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 14,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2206),
                            Rating = 5,
                            Review = "Review from user 1 - 14 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            MovieId = 15,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2209),
                            Rating = 5,
                            Review = "Review from user 1 - 15 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            MovieId = 16,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2211),
                            Rating = 5,
                            Review = "Review from user 1 - 16 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            MovieId = 17,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2214),
                            Rating = 5,
                            Review = "Review from user 1 - 17 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            MovieId = 18,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2217),
                            Rating = 5,
                            Review = "Review from user 1 - 18 ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            MovieId = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2219),
                            Rating = 5,
                            Review = "Review from user 2 - 1 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            MovieId = 2,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2222),
                            Rating = 5,
                            Review = "Review from user 2 - 2 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            MovieId = 3,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2225),
                            Rating = 5,
                            Review = "Review from user 2 - 3 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            MovieId = 4,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2228),
                            Rating = 5,
                            Review = "Review from user 2 - 4 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            MovieId = 5,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2231),
                            Rating = 5,
                            Review = "Review from user 2 - 5 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            MovieId = 6,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2234),
                            Rating = 5,
                            Review = "Review from user 2 - 6 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            MovieId = 7,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2236),
                            Rating = 5,
                            Review = "Review from user 2 - 7 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            MovieId = 8,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2239),
                            Rating = 5,
                            Review = "Review from user 2 - 8 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            MovieId = 9,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2241),
                            Rating = 5,
                            Review = "Review from user 2 - 9 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            MovieId = 10,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2244),
                            Rating = 5,
                            Review = "Review from user 2 - 10 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            MovieId = 11,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2247),
                            Rating = 5,
                            Review = "Review from user 2 - 11 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            MovieId = 12,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2249),
                            Rating = 5,
                            Review = "Review from user 2 - 12 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            MovieId = 13,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2314),
                            Rating = 5,
                            Review = "Review from user 2 - 13 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            MovieId = 14,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2317),
                            Rating = 5,
                            Review = "Review from user 2 - 14 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            MovieId = 15,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2320),
                            Rating = 5,
                            Review = "Review from user 2 - 15 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            MovieId = 16,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2323),
                            Rating = 5,
                            Review = "Review from user 2 - 16 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            MovieId = 17,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2325),
                            Rating = 5,
                            Review = "Review from user 2 - 17 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 36,
                            MovieId = 18,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2328),
                            Rating = 5,
                            Review = "Review from user 2 - 18 ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            MovieId = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2330),
                            Rating = 5,
                            Review = "Review from user 3 - 1 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 38,
                            MovieId = 2,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2333),
                            Rating = 5,
                            Review = "Review from user 3 - 2 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 39,
                            MovieId = 3,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2338),
                            Rating = 5,
                            Review = "Review from user 3 - 3 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 40,
                            MovieId = 4,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2341),
                            Rating = 5,
                            Review = "Review from user 3 - 4 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 41,
                            MovieId = 5,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2344),
                            Rating = 5,
                            Review = "Review from user 3 - 5 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 42,
                            MovieId = 6,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2346),
                            Rating = 5,
                            Review = "Review from user 3 - 6 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 43,
                            MovieId = 7,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2349),
                            Rating = 5,
                            Review = "Review from user 3 - 7 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 44,
                            MovieId = 8,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2351),
                            Rating = 5,
                            Review = "Review from user 3 - 8 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 45,
                            MovieId = 9,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2354),
                            Rating = 5,
                            Review = "Review from user 3 - 9 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 46,
                            MovieId = 10,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2357),
                            Rating = 5,
                            Review = "Review from user 3 - 10 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 47,
                            MovieId = 11,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2360),
                            Rating = 5,
                            Review = "Review from user 3 - 11 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 48,
                            MovieId = 12,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2362),
                            Rating = 5,
                            Review = "Review from user 3 - 12 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 49,
                            MovieId = 13,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2365),
                            Rating = 5,
                            Review = "Review from user 3 - 13 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 50,
                            MovieId = 14,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2368),
                            Rating = 5,
                            Review = "Review from user 3 - 14 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 51,
                            MovieId = 15,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2370),
                            Rating = 5,
                            Review = "Review from user 3 - 15 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 52,
                            MovieId = 16,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2373),
                            Rating = 5,
                            Review = "Review from user 3 - 16 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 53,
                            MovieId = 17,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2375),
                            Rating = 5,
                            Review = "Review from user 3 - 17 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 54,
                            MovieId = 18,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2378),
                            Rating = 5,
                            Review = "Review from user 3 - 18 ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 55,
                            MovieId = 1,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2381),
                            Rating = 5,
                            Review = "Review from user 4 - 1 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 56,
                            MovieId = 2,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2383),
                            Rating = 5,
                            Review = "Review from user 4 - 2 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 57,
                            MovieId = 3,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2386),
                            Rating = 5,
                            Review = "Review from user 4 - 3 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 58,
                            MovieId = 4,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2388),
                            Rating = 5,
                            Review = "Review from user 4 - 4 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 59,
                            MovieId = 5,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2391),
                            Rating = 5,
                            Review = "Review from user 4 - 5 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 60,
                            MovieId = 6,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2394),
                            Rating = 5,
                            Review = "Review from user 4 - 6 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 61,
                            MovieId = 7,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2396),
                            Rating = 5,
                            Review = "Review from user 4 - 7 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 62,
                            MovieId = 8,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2399),
                            Rating = 5,
                            Review = "Review from user 4 - 8 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 63,
                            MovieId = 9,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2402),
                            Rating = 5,
                            Review = "Review from user 4 - 9 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 64,
                            MovieId = 10,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2404),
                            Rating = 5,
                            Review = "Review from user 4 - 10 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 65,
                            MovieId = 11,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2407),
                            Rating = 5,
                            Review = "Review from user 4 - 11 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 66,
                            MovieId = 12,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2409),
                            Rating = 5,
                            Review = "Review from user 4 - 12 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 67,
                            MovieId = 13,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2412),
                            Rating = 5,
                            Review = "Review from user 4 - 13 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 68,
                            MovieId = 14,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2414),
                            Rating = 5,
                            Review = "Review from user 4 - 14 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 69,
                            MovieId = 15,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2417),
                            Rating = 5,
                            Review = "Review from user 4 - 15 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 70,
                            MovieId = 16,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2419),
                            Rating = 5,
                            Review = "Review from user 4 - 16 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 71,
                            MovieId = 17,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2422),
                            Rating = 5,
                            Review = "Review from user 4 - 17 ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 72,
                            MovieId = 18,
                            Posted = new DateTime(2022, 9, 12, 22, 53, 47, 400, DateTimeKind.Local).AddTicks(2425),
                            Rating = 5,
                            Review = "Review from user 4 - 18 ",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FavouriteGenre")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "david.pavlovski@hotmail.com",
                            FavouriteGenre = 1,
                            FirstName = "David",
                            LastName = "Pavlovski",
                            Password = "H,?????mI??I8",
                            Username = "dPavlovski"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marko.pavlovski@hotmail.com",
                            FavouriteGenre = 2,
                            FirstName = "Marko",
                            LastName = "Pavlovski",
                            Password = "H,?????mI??I8",
                            Username = "mPavlovski"
                        },
                        new
                        {
                            Id = 3,
                            Email = "rade.pavlovski@hotmail.com",
                            FavouriteGenre = 3,
                            FirstName = "Rade",
                            LastName = "Pavlovski",
                            Password = "H,?????mI??I8",
                            Username = "rPavlovski"
                        },
                        new
                        {
                            Id = 4,
                            Email = "bob.bobsky@hotmail.com",
                            FavouriteGenre = 4,
                            FirstName = "Bob",
                            LastName = "Bobsky",
                            Password = "H,?????mI??I8",
                            Username = "bBobsky"
                        });
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieDto", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.UserDto", "User")
                        .WithMany("SubmittedMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.ReviewDto", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.MovieDto", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.UserDto", "User")
                        .WithMany("SubmittedReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieDto", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserDto", b =>
                {
                    b.Navigation("SubmittedMovies");

                    b.Navigation("SubmittedReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
